modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="lightland"
version="${file.jarVersion}" #mandatory
displayName="LightLand RPG" #mandatory
logoFile="lightland.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.lightland]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lightland]]
    modId="l2library"
    mandatory=true
    versionRange="[0.0.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.lightland]]
    modId="appleskin"
    mandatory=false
    versionRange="[2.3.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.lightland]]
    modId="jei"
    mandatory=true
    versionRange="[9.7,)"
    side="CLIENT"